2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('quotes/', include('quotes.urls')),
    path('admin/', admin.site.urls),
]

2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"
urlpatterns = [
    path('', views.index, name="index"),
    path('<int:author_id>', views.detail, name="detail"),
    path('add/author', views.add_author, name="add_author"),
    path('add/quote/<int:author_id>', views.add_quote, name="add_quote")
]

2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/quotes/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

# Create your models here.
class Author(models.Model):
    author_name = models.CharField(max_length=200)
    author_bio = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.author_name

class Quote(models.Model):
    quote_text = models.CharField(max_length=200)
    author = ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.quote_text

2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/quotes/views.py
from django.shortcuts import redirect, render
import redis

from .models import Author, Quote

r = redis.StrictRedis('localhost', 6379, decode_responses=True)

# Create your views here.
def index(request):
    keys = r.keys('author:*')
    authors = []
    for key in keys:
        a = Author()
        a.id = key.split(':')[1]
        a.author_name = key.split(':')[2]
        a.author_bio = r.get(key)
        authors.append(a)

    return render(request, 'quotes/index.html', {'authors': authors})

def detail(request, author_id):
    keys = r.keys(f'author:{author_id}:*')
    key = keys[0]
    a = Author()
    a.id = int(author_id)
    a.author_name = key.split(':')[2]
    a.author_bio = r.get(key)
    quote_list = r.smembers(f'quote:{author_id}')

    return render(request, 'quotes/detail.html', {'author':a, 'quote_list': quote_list})

def add_author(request):
    if request.method == "POST":
        author_name = request.POST["author_name"]
        author_bio = request.POST["author_bio"]
        r.incr('author_count')
        r.set(f'author:{str(r.get("author_count"))}:{author_name}', author_bio)

        return redirect('/quotes')

    return render(request, 'quotes/add_author.html', {})

def add_quote(request, author_id):
    if request.method == "POST":
        quote_text = request.POST["quote_text"]
        author_id = request.POST["author_id"]

        r.sadd(f'quote:{author_id}', quote_text)

        return redirect('/quotes')

    keys = r.keys(f'author:{author_id}:*')
    key = keys[0]
    a = Author()
    a.id = int(author_id)
    a.author_name = key.split(':')[2]

    return render(request, 'quotes/add_quote.html', {'author':a})

2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/quotes/templates/quotes/add_author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Add author:</h1>

    <!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

    <form action="{% url 'quotes:add_author' %}" method="post">
        {% csrf_token %}
        <input placeholder="author name" name="author_name" type="text">
        <input placeholder="author bio" name="author_bio" type="text">
        <input type="submit" value="Add">
    </form>
</body>
</html>

2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/quotes/templates/quotes/add_quote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Add quote for {{ author.author_name }}</h1>

    <!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

    <form action="{% url 'quotes:add_quote' author.id %}" method="post">
        {% csrf_token %}
        <p>{{ author.id }}</p>
        <input placeholder="quote" name="quote_text" type="text">
        <input name="author_id" type="hidden" value="{{ author.id }}">
        <input type="submit" value="Add">
    </form>
</body>
</html>

2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/quotes/templates/quotes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Details for {{ author.author_name }}</h1>

    <ul>
    {% for quote in quote_list %}
        <li>{{ quote }}</li>
    {% endfor %}
    </ul>

    <a href="http://localhost:8000/quotes/add/quote/{{ author.id }}">Add quote</a>
</body>
</html>

2020-2021/Semester 2/Web_Services_Voorbereiding/django-redis/mysite/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>List of authors</h1>
    {% if authors %}
        <ul>
        {% for author in authors %}
            <li><a href="{% url 'quotes:detail' author.id %}">{{ author.author_name }}</a></li>
        {% endfor %}    
        </ul>
    {% endif %}
    <a href="{% url 'quotes:add_author' %}">Add author</a>
</body>
</html>