2020-2021/Examens/Web services/mysite/login/urls.py
from django.urls import path
from . import views

app_name = "login"
urlpatterns = [
    path('login', views.login, name="login"),
    path('home', views.index, name="index"),
    path('signup', views.signup, name="signup"),
]

2020-2021/Examens/Web services/mysite/mysite/urls.py
from django.urls import path
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    path('login/', include('login.urls')),
    path('admin/', admin.site.urls),
]

2020-2021/Examens/Web services/mysite/login/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user_email = models.CharField(max_length=50)
    user_password = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.user_email

2020-2021/Examens/Web services/mysite/login/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render

import hashlib

from .models import User

def index(request):
    return render(request, 'login/index.html', {})

def signup(request):
    if request.method == "POST":
        u = User()
        u.user_email = request.POST["email"]
        u.user_password = hashlib.sha1(request.POST["password"].encode('utf-8')).hexdigest()

        u.save()
        return HttpResponse("SIGNED UP", content_type="text/plain")

    return render(request, 'login/signupForm.html', {})

def login(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = hashlib.sha1(request.POST["password"].encode('utf-8')).hexdigest()
        usersFound = User.objects.filter(user_email=email).filter(user_password=password)

        # Logging in does not work in tests, but works in browser
        if(usersFound.exists()):
            return HttpResponse("LOGGED IN", content_type="text/plain")
        
        return HttpResponse("FAILED TO LOG IN", content_type="text/plain")

    
    return render(request, 'login/loginForm.html', {})

2020-2021/Examens/Web services/mysite/login/templates/login/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index page</title>
</head>
<body>
    <h1>You are on the index page!</h1>
</body>
</html>

2020-2021/Examens/Web services/mysite/login/templates/login/loginForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login page</title>
</head>
<body>
    <a href="{% url 'login:index' %}">Home</a>
    <h1>Log in with your email and password</h1>

    <!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

    <form action="{% url 'login:login' %}" method="post">
        {% csrf_token %}
        <input placeholder="someone@ap.be" name="email" type="text">
        <input placeholder="StronPassWord_453" name="password" type="text">
        <input type="submit" value="Add">
    </form>
</body>
</html>

2020-2021/Examens/Web services/mysite/login/templates/login/result.html
{{ message }}

2020-2021/Examens/Web services/mysite/login/templates/login/signupForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Signup page</title>
</head>
<body>
    <a href="{% url 'login:index' %}">Home</a>
    <h1>Sign up with an email and password</h1>

    <!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

    <form action="{% url 'login:signup' %}" method="post">
        {% csrf_token %}
        <input placeholder="someone@ap.be" name="email" type="text">
        <input placeholder="StronPassWord_453" name="password" type="text">
        <input type="submit" value="Add">
    </form>
</body>
</html>