2020-2021/Semester 2/Web_Services/Django_quotes/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:author_id>', views.detail, name="detail"),
    path('search_form', views.search_form, name="search_form"),
    path('search', views.search, name="search"),
    path('add_form', views.add_form, name="add_form"),
    path('add', views.add, name="add")
]

2020-2021/Semester 2/Web_Services/Django_quotes/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    author_name = models.CharField(max_length=50)
    author_bio = models.CharField(max_length=200)

    def __str__(self):
        return self.author_name

class Quote(models.Model):
    # FK
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    quote_text = models.CharField(max_length=200)

    def __str__(self):
        return self.quote_text

    def search_quote(self, word):
        return True if word in self.quote_text.split() else False

2020-2021/Semester 2/Web_Services/Django_quotes/quotes/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

from .models import Author, Quote

# Create your views here.
def index(request):
    authors = [a for a in Author.objects.all()]

    return render(request, 'quotes/index.html', {'authors': authors})

def detail(request, author_id):
    author = Author.objects.filter(id=author_id).first()

    return render(request, 'quotes/detail.html', {'author': author})

def search_form(request):
    return render(request, 'quotes/search_form.html', {})

def search(request):
    searchInput = request.POST['searchInput']

    searchResult = Quote.objects.filter(quote_text__contains=searchInput)

    return render(request, 'quotes/search_result.html', {
        'quotes': searchResult
    })

def add_form(request):
    return render(request, 'quotes/add_form.html', {})

def add(request):
    author_name = request.POST.get('author_name')
    author_bio = request.POST.get('author_bio')

    if(author_name=="" or author_bio==""):
        return render(request, 'quotes/add_form.html', {
            'error_message': 'please enter a name and bio'
        })

    # there is a name and bio, now add a new author
    a = Author(author_name=author_name, author_bio=author_bio)
    a.save()

    return HttpResponseRedirect(reverse('quotes:index'))

2020-2021/Semester 2/Web_Services/Django_quotes/quotes/templates/quotes/add_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Add an author</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'quotes:add' %}" method="POST">
        {% csrf_token %}
        <p>Name:</p>
        <input name="author_name" type="text">

        <p>Bio:</p>
        <input name="author_bio" type="text">

        <br>
        <input type="submit" value="Add">
    </form>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes/quotes/templates/quotes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Details for {{ author.author_name }}</h1>

    <ul>
    {% for quote in author.quote_set.all %}
        <li>{{ quote.quote_text }}</li>
    {% endfor %}
    </ul>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Author's and their quotes</h1>
    {% if authors %}
        <ul>
        {% for author in authors %}
            <li><a href="{{ author.id }}">{{ author.author_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <a href="{% url 'quotes:search_form' %}">Search quotes</a>
    <a href="{% url 'quotes:add_form' %}">Add author</a>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes/quotes/templates/quotes/search_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Search quotes:</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'quotes:search' %}" method="post">
        {% csrf_token %}
        <input name="searchInput" type="text">
        <input type="submit" value="Search">
    </form>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes/quotes/templates/quotes/search_result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Search results:</h1>
    <ul>
        {% for quote in quotes %}
            <li>{{ quote.quote_text }} ~ {{ quote.author.author_name }}</li>
        {% endfor %}
    </ul>
</body>
</html>