2020-2021/Semester 2/Web_Services/Django_quotes_redis/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('quotes/', include('quotes.urls')),
    path('admin/', admin.site.urls),
]

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:author_id>', views.detail, name="detail"),
    path('search', views.search, name="search"),
    path('search_results', views.search_results, name="search_results"),
    path('add_author', views.add_author, name="add_author"),
    path('add_author_results', views.add_author_results, name="add_author_results"),
    path('add_quote/<int:author_id>', views.add_quote, name="add_quote"),
    path('add_quote_results', views.add_quote_results, name="add_quote_results"),
    path('random_quote', views.random_quote, name="random_quote")
]

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/models.py
from django.db import models

# Create your models here.
class Author(models.Model):
    author_name = models.CharField(max_length=50)
    author_bio = models.CharField(max_length=200)

    def __str__(self):
        return self.author_name

class Quote(models.Model):
    # FK
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    quote_text = models.CharField(max_length=200)

    def __str__(self):
        return self.quote_text

    def search_quote(self, word):
        return True if word.lower() in self.quote_text.lower().replace('.', '').split() else False

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/views.py
from django.shortcuts import render, redirect
import string
import redis
import random

from .models import Author, Quote

r = redis.StrictRedis('localhost', 6379, decode_responses=True)

# Create your views here.
def index(request):
    keys = r.keys('author:*')
    authors = []
    for key in keys:
        a = Author()
        a.id = key.split(':')[1]
        a.author_name = key.split(':')[2]
        a.author_bio = r.get(key)
        authors.append(a)

    return render(request, 'quotes/index.html', {'authors': authors})

def detail(request, author_id):
    keys = r.keys('author:' + str(author_id) + ':*')
    key = keys[0]
    a = Author()
    a.id = int(author_id)
    a.author_name = key.split(':')[2]
    a.author_bio = r.get(key)
    quote_list = r.smembers('quote:' + str(author_id))

    return render(request, 'quotes/detail.html', {'author': a, 'quote_list': quote_list})

def search(request):
    return render(request, 'quotes/search.html', {})

def search_results(request):
    quote_list = []
    if request.method == 'POST':
        word = request.POST['word']
        quotes = r.keys('quote:*')
        for txt in quotes:
            author_id = key.split(':')[2]
            for quote in r.smembers(key):
                q = Quote()
                q.quote_text = txt
                if q.search_quote(word):
                    quote_list.append(q.quote_text + '-' + r.keys('author:' + author_id + ':*')[0].split(':')[2])
    
    print(quote_list)
    return render(request, 'quotes/search_results.html', {'quote_list': quote_list})

def add_author(request):
    return render(request, 'quotes/add_author_form.html', {})

def add_author_results(request):
    if request.method == 'POST':
        author_name = request.POST['author_name']
        author_bio = request.POST['author_bio']
        r.incr('author_count')
        r.set('author:' + str(r.get('author_count')) + ':' + author_name, author_bio) # author:[id]:[name]

    return redirect('http://localhost:8000/quotes')

def add_quote(request, author_id):
    keys = r.keys('author:' + str(author_id) + ':*')
    key = keys[0]
    a = Author()
    a.id = int(author_id)
    a.author_name = key.split(':')[2]

    return render(request, 'quotes/add_quote_form.html', {'author': a})

def add_quote_results(request):
    if request.method == 'POST':
        quote_text = request.POST['quote_text']
        author_id = request.POST['author_id']
        r.sadd('quote:' + str(author_id), quote_text) # quote:[id]
    
    return redirect('http://localhost:8000/quotes')

def random_quote(request):
    quote_key = ""
    while(quote_key.find('quote') == -1):
        quote_key = r.randomkey()

    quote = random.choice(tuple(r.smembers(quote_key)))
    quote += '-' + r.keys('author:' + quote_key.split(':')[1] + ':*')[0].split(':')[2]

    return render(request, 'quotes/search_result.html', {'quote_list': [quote]})

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/templates/quotes/add_author_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Add author:</h1>

    <!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

    <form action="{% url 'quotes:add_author_results' %}" method="post">
        {% csrf_token %}
        <input placeholder="author name" name="author_name" type="text">
        <input placeholder="author bio" name="author_bio" type="text">
        <input type="submit" value="Add">
    </form>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/templates/quotes/add_quote_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Add quote for {{ author.author_name }}</h1>

    <!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

    <form action="{% url 'quotes:add_quote_results' %}" method="post">
        {% csrf_token %}
        <input placeholder="quote" name="quote_text" type="text">
        <input name="author_id" type="hidden" value="{{ author.id }}">
        <input type="submit" value="Add">
    </form>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/templates/quotes/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Details for {{ author.author_name }}</h1>

    <ul>
    {% for quote in quote_list %}
        <li>{{ quote }}</li>
    {% endfor %}
    </ul>

    <a href="http://localhost:8000/quotes/add_quote/{{ author.id }}">Add quote</a>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/templates/quotes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Author's and their quotes</h1>
    {% if authors %}
        <ul>
        {% for author in authors %}
            <li><a href="{{ author.id }}">{{ author.author_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No authors are available.</p>
    {% endif %}
    <a href="{% url 'quotes:search' %}">Search quotes</a>
    <a href="{% url 'quotes:add_author' %}">Add author</a>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/templates/quotes/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Search quotes:</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'quotes:search_results' %}" method="post">
        {% csrf_token %}
        <input name="word" type="text">
        <input type="submit" value="Search">
    </form>
</body>
</html>

2020-2021/Semester 2/Web_Services/Django_quotes_redis/quotes/templates/quotes/search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quotes</title>
</head>
<body>
    <a href="{% url 'quotes:index' %}">Home</a>
    <h1>Search results:</h1>
    <ul>
        {% for quote in quote_list %}
            <li>{{ quote.quote_text }} ~ {{ quote.author.author_name }}</li>
        {% endfor %}
    </ul>
</body>
</html>